# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require_relative '../node_modules/react-native/scripts/react_native_pods' 
platform :ios, '9.0'
target 'timerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for timerDemo

  target 'timerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
